---
# tasks file for destroy_vms
- name: Stop VMs
  community.general.lxd_container:
    name: "{{ item }}"
    state: stopped
    force_stop: true
    type: virtual-machine
  with_items: " {{ groups['instances'] }}"
